import theme1 from '../Assets/themes/midorima.png';
import theme2 from '../Assets/themes/akashi.png';
import theme3 from '../Assets/themes/kuroko.png';
import theme4 from '../Assets/themes/giannis.png';
import theme5 from '../Assets/themes/tatum.png';
import theme6 from '../Assets/themes/james.png';
import theme7 from '../Assets/themes/paul.png';
import theme8 from '../Assets/themes/george.png';
import theme9 from '../Assets/themes/lillard.png';

export const themes = [
  {
    id: 1,
    img: theme1,
    title: 'Theme 1',
    bgHeader: 'bg-[#fff]',
    bgContent: 'bg-[#D4D9E3]',
    bgBottom: 'bg-[#DEE4EB]',
    bgPrimary: 'bg-gradient-to-b from-[#3C5D60] to-[#2E4748]',
    bgPrimaryAlpha: 'bg-gradient-to-b from-[#3C5D60] to-[#2E4748]',
    bgSecond: 'bg-gradient-to-b from-[#BFCCCC] to-[#ECEEF0]',
    bgSecondAlpha: 'bg-gradient-to-b from-[#BFCCCCCC] to-[#ECEEF0CC]',
    color: 'text-[#111]',
    colorNumberShirt: 'text-[#3B5E60]',
    colorPosition: 'text-[#3B5E60]',
    colorBottom: 'text-black',
    colorRebounds: 'text-[#3B5E60]',
  },
  {
    id: 2,
    img: theme2,
    title: 'Theme 2',
    bgHeader: 'bg-[#fff]',
    bgContent: 'bg-gradient-to-b from-[#A42D53] to-[#DA6277]',
    bgBottom: 'bg-[#072E4F]',
    bgPrimary: 'bg-[#041f35]',
    bgPrimaryAlpha: 'bg-gradient-to-b from-[#041f35CC] to-[#041f35CC]',
    bgSecond: 'bg-gradient-to-b from-[#BFCCCC] to-[#ECEEF0]',
    bgSecondAlpha: 'bg-gradient-to-b from-[#0c4472CC] to-[#0c4472CC]',
    color: 'text-[#111]',
    colorNumberShirt: 'text-[#0c4a7c]',
    colorPosition: 'text-[#0c4a7c]',
    colorBottom: 'text-white',
    colorRebounds: 'text-[#fff]',
  },
  {
    id: 3,
    img: theme3,
    title: 'Theme 3',
    bgHeader: 'bg-[#fff]',
    bgContent: 'bg-gradient-to-b from-[#0D68D9] to-[#C7DFF1]',
    bgBottom: 'bg-[#00045e]',
    bgPrimary: 'bg-[#00033f]',
    bgPrimaryAlpha: 'bg-gradient-to-b from-[#00033fCC] to-[#00033fCC]',
    bgSecond: 'bg-gradient-to-b from-[#BFCCCC] to-[#ECEEF0]',
    bgSecondAlpha: 'bg-gradient-to-b from-[#161c7fCC] to-[#161c7fCC]',
    color: 'text-[#111]',
    colorNumberShirt: 'text-[#00045E]',
    colorPosition: 'text-[#00045E]',
    colorBottom: 'text-white',
    colorRebounds: 'text-[#fff]',
  },

  {
    id: 4,
    img: theme4,
    title: 'Theme 4',
    bgHeader: 'bg-[#fff]',
    bgContent: 'bg-gradient-to-b from-[#DD69EE] to-[#DDA6B0]',
    bgBottom: 'bg-[#3B0967]',
    bgPrimary: 'bg-[#280747]',
    bgPrimaryAlpha: 'bg-[#280747CC]',
    bgSecond: 'bg-[#5c11a3]',
    bgSecondAlpha: 'bg-[#5c11a3CC]',
    color: 'text-[#111]',
    colorNumberShirt: 'text-[#321835]',
    colorPosition: 'text-[#321835]',
    colorBottom: 'text-white',
    colorRebounds: 'text-[#fff]',
  },
  {
    id: 5,
    img: theme5,
    title: 'Theme 5',
    bgHeader: 'bg-[#fff]',
    bgContent: 'bg-gradient-to-b from-[#3B7D5F] to-[#63cc9b]',
    bgBottom: 'bg-[#202124]',
    bgPrimary: 'bg-[#0e1c15]',
    bgPrimaryAlpha: 'bg-[#0e1c15CC]',
    bgSecond: 'bg-[#52b285]',
    bgSecondAlpha: 'bg-[#52b285CC]',
    color: 'text-[#111]',
    colorNumberShirt: 'text-[#202124]',
    colorPosition: 'text-[#202124]',
    colorBottom: 'text-white',
    colorRebounds: 'text-[#fff]',
  },
  {
    id: 6,
    img: theme6,
    title: 'Theme 6',
    bgHeader: 'bg-[#fff]',
    bgContent: 'bg-gradient-to-b from-[#EDB623] to-[#D7D0C2]',
    bgBottom: 'bg-[#31154B]',
    bgPrimary: 'bg-[#512582]',
    bgPrimaryAlpha: 'bg-[#512582CC]',
    bgSecond: 'bg-[#301646]',
    bgSecondAlpha: 'bg-[#301646CC]',
    color: 'text-[#111]',
    colorNumberShirt: 'text-[#E1484B]',
    colorPosition: 'text-[#E1484B]',
    colorBottom: 'text-white',
    colorRebounds: 'text-[#fff]',
  },
  {
    id: 7,
    img: theme7,
    title: 'Theme 7',
    bgHeader: 'bg-[#fff]',
    bgContent: 'bg-[#E5E7EA]',
    bgBottom: 'bg-[#C2C6CB]',
    bgPrimary: 'bg-[#AB2B2C]',
    bgPrimaryAlpha: 'bg-[#AB2B2CCC]',
    bgSecond: 'bg-[#212736]',
    bgSecondAlpha: 'bg-[#212736CC]',
    color: 'text-[#111]',
    colorNumberShirt: 'text-[#E1484B]',
    colorPosition: 'text-[#E1484B]',
    colorBottom: 'text-black',
    colorRebounds: 'text-[#fff]',
  },
  {
    id: 8,
    img: theme8,
    title: 'Theme 8',
    bgHeader: 'bg-[#fff]',
    bgContent: 'bg-[#E5E7EA]',
    bgBottom: 'bg-[#C2C6CB]',
    bgPrimary: 'bg-[#1D4ED2]',
    bgPrimaryAlpha: 'bg-[#1D4ED2CC]',
    bgSecond: 'bg-[#161516]',
    bgSecondAlpha: 'bg-[#161516CC]',
    color: 'text-[#111]',
    colorNumberShirt: 'text-[#E1484B]',
    colorPosition: 'text-[#E1484B]',
    colorBottom: 'text-black',
    colorRebounds: 'text-[#fff]',
  },
  {
    id: 9,
    img: theme9,
    title: 'Theme 9',
    bgHeader: 'bg-[#fff]',
    bgContent: 'bg-gradient-to-b from-[#A90A11] to-[#ffbabe]',
    bgBottom: 'bg-[#1c0304]',
    bgPrimary: 'bg-[#070203]',
    bgPrimaryAlpha: 'bg-[#070203CC]',
    bgSecond: 'bg-[#f25c61]',
    bgSecondAlpha: 'bg-[#f25c61CC]',
    color: 'text-[#111]',
    colorNumberShirt: 'text-[#1c0304]',
    colorPosition: 'text-[#1c0304]',
    colorBottom: 'text-white',
    colorRebounds: 'text-[#fff]',
  },
];
